#!/bin/bash

jupyter labextension install nbdime-jupyterlab --no-build && \
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build && \
jupyter labextension install jupyter-matplotlib --no-build && \
jupyter labextension install @jupyterlab/debugger --no-build && \
jupyter labextension install jupyter-leaflet --no-build && \
jupyter lab build 
